In [12]:
import numpy as np
a=np.array([1,2,4])
print(a)
type(a)

[1 2 4]


numpy.ndarray

In [13]:
b=np.array(([1,2,3],[4,5,6],[8,9,3]))
print(b)

[[1 2 3]
 [4 5 6]
 [8 9 3]]


In [7]:
type(a)

numpy.ndarray

In [16]:
total_sum=0
for row in b:
    for element in row:
        total_sum+= element
print(total_sum)        
        

41


In [18]:
total_diff=0
for row in b:
    for element in row:
        total_diff-= element
print(total_diff)

-41


In [19]:
c=np.array([[6,8,3],[5,3,7],[4,1,2]])
print(c)

[[6 8 3]
 [5 3 7]
 [4 1 2]]


In [22]:
result=b + c
print(result)

[[ 7 10  6]
 [ 9  8 13]
 [12 10  5]]


In [23]:
result=b-c
print(result)

[[-5 -6  0]
 [-1  2 -1]
 [ 4  8  1]]


In [24]:
result=b*c
print(result)

[[ 6 16  9]
 [20 15 42]
 [32  9  6]]


In [25]:
result=b/c
print(result)

[[0.16666667 0.25       1.        ]
 [0.8        1.66666667 0.85714286]
 [2.         9.         1.5       ]]


In [28]:
b=np.array(([1,2,3],[4,5,6],[8,9,3]))
c=np.array([[6,8,3],[5,3,7],[4,1,2]])
np.add(c+b)

    

ValueError: invalid number of arguments