In [7]:
#create a 4*4 array with random values and creat a new array after swapping 1st and last row#

import numpy as np
nums=np.arange(16,dtype='int').reshape(-1,4)
print("original array:")
print(nums)
print("\nnew array after swapping frist and last rows of the said array:")
#new_nums=nums[3:3:-1]
nums=nums[[-1,1,2,0]]
print(nums)

original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

new array after swapping frist and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [2]:
#save a given array to a text file and load it arr.text---

import numpy as np
import os
x=np.arange(16).reshape(4,4)
print("array")
print(x)
header='C1 C2 C3 C4'
np.savetxt('7_array.txt',x,fmt="%d",header=header)
print("\n after loading,content of the text file")
print(np.loadtxt('7_array.txt'))

array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 after loading,content of the text file
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
